name: Github-CI
on: [push, pull_request]
jobs:
    generator-jhipster:
        name: JHipster generator test suite
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node_version: [10.16.3]
                os: [ubuntu-latest]
        steps:
            env:
                JHI_PROFILE: dev
                JHI_RUN_APP: 1
                JHI_PROTRACTOR: 0
                JHI_JDK: 11
                # if JHI_LIB_BRANCH value is release, use the release from Maven
                JHI_LIB_REPO: https://github.com/jhipster/jhipster.git
                JHI_LIB_BRANCH: release
                # if JHI_GEN_BRANCH value is release, use the release from NPM
                JHI_GEN_REPO: https://github.com/jhipster/generator-jhipster.git
                JHI_GEN_BRANCH: master
                # specific config
                SPRING_OUTPUT_ANSI_ENABLED: ALWAYS
                SPRING_JPA_SHOW_SQL: false
                JHI_DISABLE_WEBPACK_LOGS: true
                JHI_E2E_HEADLESS: true
                JHI_SCRIPTS=: ./test-integration/scripts
                NG_CLI_ANALYTICS: false
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node_version }}
            - run: git --no-pager log -n 10 --graph --pretty='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue) <%an>%Creset' --abbrev-commit
              shell: bash
            - run: $JHI_SCRIPTS/04-git-config.sh
              shell: bash
            - run: npm ci
            - run: npm test
